# Name of your application. Used to uniquely configure containers.
service: umami

# Name of the container image.
image: loop-i/umami-lo7d

# Deploy to these servers.
servers:
  web:
    - 100.112.248.60

proxy:
  ssl: true
  host: umami.lo7d.de
  healthcheck:
    path: /

registry:
  server: ghcr.io
  username: loop-i
  password:
    - KAMAL_REGISTRY_PASSWORD

ssh:
  user: deploy

env:
  clear:
    PORT: 3000
  secret:
    - DATABASE_URL

accessories:
  db:
    image: postgres:16-alpine
    host: 100.112.248.60
    port: 5432
    env:
      clear:
        POSTGRES_DB: umami
        POSTGRES_USER: umami
      secret:
        - POSTGRES_PASSWORD
    volumes:
      - /var/lib/umami/postgres:/var/lib/postgresql/data
